set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

default:
    @just --list

setup:
    npm ci

dev:
    npm run dev

fmt:
    npm run format --if-present

lint:
    npm run lint --if-present

test:
    npm test --if-present

build:
    npm run build --if-present

ci: fmt lint test build
